name: Docker Image Publish

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: docker/login-action@v3
      with:
        # Container registry username
        username: ${{ secrets.SAMPLEAPP_ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.SAMPLEAPP_ACR_PASSWORD }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag eschweighofer/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag eschweighofer/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER eschweighofer/sample-app-aoai-chatgpt:latest;
        docker push eschweighofer/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push eschweighofer/sample-app-aoai-chatgpt:latest;
      
